### ISSUE TITLE
About downloading preprocessed data

### ISSUE THREAD

**Issue by JokerHYX-719** [Graph-and-Geometric-Learning/HyBRiD#2]
It seems that your gitlfs quota is not enough, I can't clone preprocessed data.Is there another place to download preprocessed data?

**Comment by Boltzmachine** [comment]
Hi, we also offer a google drive link in the readme.

**Comment by mxia96** [comment]
Hi, I did not see all the file in google drive. I only find files train.split and test.split

**Comment by Boltzmachine** [comment]
Oh my god sorry for the mistake. I just uploaded it. Please do not hesitate to contact me if you have further questions

**Comment by mxia96** [comment]
> Oh my god sorry for the mistake. I just uploaded it. Please do not hesitate to contact me if you have further questions

Thank you.
