### ISSUE TITLE
hyperedge do not overlap

### ISSUE THREAD

**Issue by mxia96** [Graph-and-Geometric-Learning/HyBRiD#3]
Below the equation 10, 'The equality holds if and only if nodes are independent and hyperedges do not overlap.' What does it means? Does it mean that two hyperedges could not be same or one nodes could not in two hyperedges?

**Comment by Boltzmachine** [comment]
No. Please refere to https://openreview.net/forum?id=WC14xZIaC2&noteId=3t3hSwEsK7 R1
